### ISSUE TITLE
Add a liability waiver/membership agreement to the sign-up process.

### ISSUE THREAD

**Issue by cndreisbach** [greentogo/greentogo#107]
https://trello.com/c/eYSvfGvS/64-add-a-liability-waiver-membership-agreement-to-the-sign-up-process

Agreement/waiver: https://docs.google.com/document/d/1Vrb5Hkx7YtoJo0DLjFkk4Uq0k5FIWJtjtmaF39Eg7Tw/edit

**Comment by jtcanfield** [comment]
Resolved a long time ago
