### ISSUE TITLE
Remove `beta_signup` application from project

### ISSUE THREAD

**Issue by cndreisbach** [greentogo/greentogo#117]
This was the original app, and is no longer used.

![bitmoji](https://render.bitstrips.com/v2/cpanel/78c42cac-21bc-4a9b-b511-ac7abf0cec89-bb69060c-eccd-4c08-a1d6-595d0b37616d-v1.png?transparent=1&palette=1&width=246)

**Comment by jtcanfield** [comment]
I'll work on this!
