### ISSUE TITLE
Improve admin dashboard checkin/checkout indicators

### ISSUE THREAD

**Issue by cndreisbach** [greentogo/greentogo#125]
How many boxes are still in inventory at each restaurant, with green (60%+), yellow (40-59%), and red (<40%) indicators
How many boxes are checked in at each individual return station with green (<10), yellow (10-20), and red (21+) indicators

**Comment by jtcanfield** [comment]
Resolved with recent updates to charts #97405c60fa1e1ecbe23e2e7c58236a4fa4ea514f
