### ISSUE TITLE
Add ability for drivers to record pick-up/drop-off actuals

### ISSUE THREAD

**Issue by cndreisbach** [greentogo/greentogo#126]
See /admin/restock_locations/ and /admin/empty_locations/

**Comment by setphen** [comment]
I added User Groups to the admin, so that a "Driver" group can be created, with permissions to only see the restock_locations and empty_location fields

**Comment by setphen** [comment]
I misunderstood part of this issue. I'll add a clearer way for the driver to report stock count when they reset.

**Comment by setphen** [comment]
Staff should now use the frontend stock reporting page.

Currently this exists, but needs to be separated into two categories (Restock and Empty).

This page creates a stock count – the same as the action in the admin - but also creates a stock _report_, which keeps track of the actual and estimated number of boxes at a location when the stock count is set.

**Comment by jtcanfield** [comment]
Finished
