### ISSUE TITLE
Make purchases have clearer info fields in Stripe

### ISSUE THREAD

**Issue by cndreisbach** [greentogo/greentogo#132]

**Comment by setphen** [comment]
unlike one-time charges, Stripe's API for creating subscriptions does not seem to have a `description` field.

I could include a description in the `metadata` field, but I don't think this would make the Stripe admin interface any clearer.

https://stripe.com/docs/api/python#subscriptions

**Comment by setphen** [comment]
The metadata field would only apply to subscriptions, but the problem is that automatic payments made via a new subscription have an automatically generated description. I don't think there is a way to achieve the desired outcome here.
