### ISSUE TITLE
Add email notification system for subscriptions soon expiring

### ISSUE THREAD

**Issue by cndreisbach** [greentogo/greentogo#134]

**Comment by setphen** [comment]
Correct me if I'm wrong, but I think this will require some additional setup outside of Django, for task scheduling (cron, or Celery).

Perhaps there is a Django-only way to set up a task to check for subscriptions expiring in X days, every day, and send emails – but I'm not aware of it.

**Comment by cndreisbach** [comment]
This is correct. I haven't dealt with Celery in the past, but I bet we could figure it out together. Do you want to schedule a time to meet and figure out what we need?

**Comment by jtcanfield** [comment]
Resolved.
