### ISSUE TITLE
Some users have a subscription in Stripe, but a blank Stripe_ID field in Django.

### ISSUE THREAD

**Issue by setphen** [greentogo/greentogo#139]
This is due to a time when users were manually given Stripe subscriptions before the Django app was complete, and therefor their Stripe sub is not synced with their account on the website.

If we can identify these users, perhaps we can sync them with Stripe by matching customer email addresses.

**Comment by jtcanfield** [comment]
Partially Resolved by commit cf973a934ebbf9e2f6ce99d27d4efaf39e411702. This only works for people with one subscription ever. If there are more than one, there is no way to relate them other than start and end dates, and I have yet to add that in.

**Comment by jtcanfield** [comment]
Resolved, all users sync'ed
