### ISSUE TITLE
Create a coupon system

### ISSUE THREAD

**Issue by cndreisbach** [greentogo/greentogo#73]
https://trello.com/c/oiepttwM/69-create-a-coupon-system

**Comment by cndreisbach** [comment]
Example: 24-hour coupon code for $5 off first year

**Comment by cndreisbach** [comment]
Other examples:

Value:  (as a % or $ off) 
Limit to one redemption per person 
Limit to certain email address 
Limit by an expiration date

**Comment by setphen** [comment]
Coupon system added, with options described above ^
