### ISSUE TITLE
Create report -- How many people checked out boxes in the last week? In the last month?

### ISSUE THREAD

**Issue by cndreisbach** [greentogo/greentogo#74]
https://trello.com/c/EpMrLUVJ/84-create-report-how-many-people-checked-out-boxes-in-the-last-week-in-the-last-month

**Comment by setphen** [comment]
I created a chart in the activity report to show the % of subscriptions (subs with one or more checkin/out) over the past 30 days. Currently this is calculated using the total number of subscriptions, but it needs to be limited to the _active_ subscriptions, to avoid under-reporting.
