### ISSUE TITLE
Add export for all tables in admin

### ISSUE THREAD

**Issue by cndreisbach** [greentogo/greentogo#76]
https://trello.com/c/YPRTywOc/85-add-export-for-all-tables-in-admin

**Comment by setphen** [comment]
This may be handled better by a flexible third-party app such as [django-export-action](https://github.com/fgmacedo/django-export-action) which automatically traverses foreign keys, giving a more useful dataset.

I'll give it a try.

**Comment by setphen** [comment]
django-export-action is meant to interface with the default `admin.site`, so I had to register it's action to the custom admin site, and register all the core models with the default admin site in order to get it working, but it seems to be doing the trick.
