### ISSUE TITLE
Add way to reset someone's checkouts

### ISSUE THREAD

**Issue by cndreisbach** [greentogo/greentogo#77]
https://trello.com/c/CcBi1KsQ/71-add-way-to-reset-someones-checkouts

**Comment by setphen** [comment]
I've added an admin action that will create a check-in LocationTag for each checked-out box. Currently I have it choose the first checkin location it finds.

To keep that location from over-reporting their stock (if LocationTags are used to calculate stock), perhaps we could create a class of location that only relates to administration. Sort of like a black-hole where all reset checkouts will go 😸 

```
if sub.can_checkin():
            #Create checkin tags equal to number of boxes currently checked out
            for i in range(sub.boxes_checked_out()):
                # Use the first checkin LocationTag
                LocationTag.objects.create(subscription=sub, location=Location.objects.checkin().first())
```
