### ISSUE TITLE
Add motivational info that customers receive every time they check a box in.

### ISSUE THREAD

**Issue by cndreisbach** [greentogo/greentogo#82]
https://trello.com/c/XVwZOqRz/67-add-motivational-info-that-customers-receive-every-time-they-check-a-box-in

**Comment by cndreisbach** [comment]
Personal contribution + total contribution

**Comment by jtcanfield** [comment]
Resolved by 6efb2e42d27a2c353ef11103998088affb7a2ba1 , b0b40f9dc1d43e3ea8b538f16cc7ac0abda17895 , 363df811da627bf3542be466371672f225138304 , 900295c3136553adf1a0c4a11b71e4d49895ff5d
