### ISSUE TITLE
Allow users to cancel subscriptions

### ISSUE THREAD

**Issue by cndreisbach** [greentogo/greentogo#90]
https://trello.com/c/sNU70WY6/47-allow-users-to-cancel-subscriptions

**Comment by setphen** [comment]
Cancellation means cancelling auto-renew. No prorated refund.

**Comment by setphen** [comment]
method: retrieve and delete subscription. Set at_period_end=True to allow users to finish the period of their subscription, which will then _not_ be renewed.

https://stripe.com/docs/api/python#cancel_subscription

todo:
create a view+template for users to cancel their subscriptions.

**Comment by setphen** [comment]
Template for cancellation is complete. Let's make it less "discoverable" (i.e. harder to do).
